-- 03-snowflake-integration/sql/analytics_views.sql
-- Daily trade summary view
CREATE OR REPLACE VIEW TRADE_DB.ANALYTICS.DAILY_TRADE_SUMMARY AS
SELECT
    DATE(TRADE_DATE) as TRADE_DATE,
    COUNT(*) as TOTAL_TRADES,
    COUNT(DISTINCT TRADE_ID) as UNIQUE_TRADES,
    COUNT(DISTINCT COUNTERPARTY_ID) as UNIQUE_COUNTERPARTIES,
    SUM(QUANTITY) as TOTAL_QUANTITY,
    SUM(QUANTITY * PRICE) as TOTAL_VALUE,
    AVG(PRICE) as AVG_PRICE,
    SUM(CASE WHEN TRADE_TYPE = 'BUY' THEN QUANTITY ELSE 0 END) as BUY_QUANTITY,
    SUM(CASE WHEN TRADE_TYPE = 'SELL' THEN QUANTITY ELSE 0 END) as SELL_QUANTITY,
    COUNT(CASE WHEN STATUS = 'EXPIRED' THEN 1 END) as EXPIRED_TRADES,
    COUNT(CASE WHEN STATUS = 'REJECTED' THEN 1 END) as REJECTED_TRADES
FROM TRADE_DB.PROCESSED.VALID_TRADES
WHERE IS_CURRENT = TRUE
GROUP BY DATE(TRADE_DATE)
ORDER BY TRADE_DATE DESC;

-- Counterparty risk exposure view
CREATE OR REPLACE VIEW TRADE_DB.ANALYTICS.COUNTERPARTY_RISK AS
WITH counterparty_exposure AS (
    SELECT
        COUNTERPARTY_ID,
        INSTRUMENT_ID,
        CURRENCY,
        SUM(CASE WHEN TRADE_TYPE = 'BUY' THEN QUANTITY * PRICE 
                ELSE -QUANTITY * PRICE END) as NET_EXPOSURE,
        SUM(QUANTITY * PRICE) as GROSS_EXPOSURE,
        COUNT(*) as TRADE_COUNT,
        MIN(TRADE_DATE) as FIRST_TRADE_DATE,
        MAX(TRADE_DATE) as LAST_TRADE_DATE
    FROM TRADE_DB.PROCESSED.VALID_TRADES
    WHERE IS_CURRENT = TRUE
        AND STATUS = 'VALID'
    GROUP BY COUNTERPARTY_ID, INSTRUMENT_ID, CURRENCY
)
SELECT
    COUNTERPARTY_ID,
    INSTRUMENT_ID,
    CURRENCY,
    NET_EXPOSURE,
    GROSS_EXPOSURE,
    TRADE_COUNT,
    FIRST_TRADE_DATE,
    LAST_TRADE_DATE,
    CASE 
        WHEN ABS(NET_EXPOSURE) > 1000000 THEN 'HIGH'
        WHEN ABS(NET_EXPOSURE) > 100000 THEN 'MEDIUM'
        ELSE 'LOW'
    END as RISK_LEVEL
FROM counterparty_exposure
ORDER BY ABS(NET_EXPOSURE) DESC;

-- Materialized view for fast dashboard queries
CREATE OR REPLACE MATERIALIZED VIEW TRADE_DB.ANALYTICS.HOURLY_TRADE_METRICS
CLUSTER BY (TRADE_HOUR, COUNTERPARTY_ID)
AS
SELECT
    DATE_TRUNC('HOUR', TRADE_DATE) as TRADE_HOUR,
    COUNTERPARTY_ID,
    COUNT(*) as TRADE_COUNT,
    SUM(QUANTITY) as TOTAL_QUANTITY,
    SUM(QUANTITY * PRICE) as TOTAL_VALUE,
    APPROX_PERCENTILE(PRICE, 0.5) as MEDIAN_PRICE,
    STDDEV(PRICE) as PRICE_VOLATILITY
FROM TRADE_DB.PROCESSED.VALID_TRADES
WHERE IS_CURRENT = TRUE
    AND STATUS = 'VALID'
    AND TRADE_DATE >= DATEADD('DAY', -30, CURRENT_TIMESTAMP())
GROUP BY DATE_TRUNC('HOUR', TRADE_DATE), COUNTERPARTY_ID;

-- Compliance reporting view
CREATE OR REPLACE VIEW TRADE_DB.ANALYTICS.COMPLIANCE_REPORT AS
SELECT
    'REJECTED' as CATEGORY,
    REJECTION_REASON,
    COUNT(*) as COUNT,
    MIN(REJECTED_AT) as FIRST_REJECTION,
    MAX(REJECTED_AT) as LAST_REJECTION
FROM TRADE_DB.AUDIT.REJECTED_TRADES
WHERE DATE(REJECTED_AT) >= DATEADD('DAY', -7, CURRENT_DATE())
GROUP BY REJECTION_REASON

UNION ALL

SELECT
    'EXPIRED' as CATEGORY,
    'MATURITY_DATE_PASSED' as REASON,
    COUNT(*) as COUNT,
    MIN(EXPIRED_AT) as FIRST_EXPIRY,
    MAX(EXPIRED_AT) as LAST_EXPIRY
FROM TRADE_DB.PROCESSED.EXPIRED_TRADES
WHERE DATE(EXPIRED_AT) >= DATEADD('DAY', -7, CURRENT_DATE())

ORDER BY COUNT DESC;

-- Real-time dashboard view
CREATE OR REPLACE VIEW TRADE_DB.ANALYTICS.REAL_TIME_DASHBOARD AS
SELECT
    CURRENT_TIMESTAMP() as REFRESH_TIME,
    (SELECT COUNT(*) FROM TRADE_DB.PROCESSED.VALID_TRADES 
     WHERE IS_CURRENT = TRUE 
       AND TRADE_DATE >= DATEADD('HOUR', -1, CURRENT_TIMESTAMP())) as TRADES_LAST_HOUR,
    
    (SELECT SUM(QUANTITY * PRICE) FROM TRADE_DB.PROCESSED.VALID_TRADES 
     WHERE IS_CURRENT = TRUE 
       AND TRADE_DATE >= DATEADD('HOUR', -1, CURRENT_TIMESTAMP())) as VOLUME_LAST_HOUR,
    
    (SELECT COUNT(*) FROM TRADE_DB.AUDIT.REJECTED_TRADES 
     WHERE REJECTED_AT >= DATEADD('HOUR', -1, CURRENT_TIMESTAMP())) as REJECTIONS_LAST_HOUR,
    
    (SELECT COUNT(DISTINCT COUNTERPARTY_ID) FROM TRADE_DB.PROCESSED.VALID_TRADES 
     WHERE IS_CURRENT = TRUE 
       AND TRADE_DATE >= DATEADD('HOUR', -24, CURRENT_TIMESTAMP())) as ACTIVE_COUNTERPARTIES,
    
    (SELECT AVG(PRICE) FROM TRADE_DB.PROCESSED.VALID_TRADES 
     WHERE IS_CURRENT = TRUE 
       AND TRADE_DATE >= DATEADD('MINUTE', -15, CURRENT_TIMESTAMP())) as AVG_PRICE_LAST_15MIN;
