
-- 03-snowflake-integration/tasks-streams/create_streams.sql
-- Following operations are done within this SQL scripts
-- Create stream on staging table
-- Create stream on valid trades for change tracking
-- Create task to process raw trades 
-- Merge new trades into processed table
-- Create task for data quality checks viz. Duplicate trades, future date trades, expired trade detection (move to expired trades table)
-- Initiate tasks to RESUME state
--



-- Create stream on staging table
CREATE OR REPLACE STREAM TRADE_DB.RAW.TRADES_STREAM 
ON TABLE TRADE_DB.RAW.TRADES_STAGING
COMMENT = 'CDC stream for new trade records';

-- Create stream on valid trades for change tracking
CREATE OR REPLACE STREAM TRADE_DB.PROCESSED.VALID_TRADES_STREAM 
ON TABLE TRADE_DB.PROCESSED.VALID_TRADES
APPEND_ONLY = TRUE
COMMENT = 'Stream for new valid trades';

-- Create task to process raw trades
CREATE OR REPLACE TASK TRADE_DB.PROCESSED.PROCESS_NEW_TRADES
  WAREHOUSE = TRADE_TRANSFORM_WH
  SCHEDULE = '5 MINUTE'
AS
BEGIN
  -- Merge new trades into processed table
  MERGE INTO TRADE_DB.PROCESSED.VALID_TRADES vt
  USING (
    SELECT 
      RAW_DATA: trade_id::STRING as TRADE_ID,
      RAW_DATA: version::INTEGER as VERSION,
      RAW_DATA: counterparty_id::STRING as COUNTERPARTY_ID,
      RAW_DATA: instrument_id::STRING as INSTRUMENT_ID,
      RAW_DATA: quantity::INTEGER as QUANTITY,
      RAW_DATA: price::DECIMAL(20,6) as PRICE,
      RAW_DATA: trade_type::STRING as TRADE_TYPE,
      RAW_DATA: currency::STRING as CURRENCY,
      RAW_DATA: trade_date::TIMESTAMP_TZ as TRADE_DATE,
      RAW_DATA: maturity_date::TIMESTAMP_TZ as MATURITY_DATE,
      CURRENT_TIMESTAMP() as PROCESSED_AT,
      'SNOWPIPE_LOAD' as LOAD_SOURCE
    FROM TRADE_DB.RAW.TRADES_STREAM
    WHERE METADATA$ACTION = 'INSERT'
  ) src
  ON vt.TRADE_ID = src.TRADE_ID AND vt.IS_CURRENT = TRUE
  WHEN MATCHED AND src.VERSION > vt.VERSION THEN
    UPDATE SET 
      vt.IS_CURRENT = FALSE,
      vt.VALID_TO = CURRENT_TIMESTAMP(),
      vt.UPDATED_AT = CURRENT_TIMESTAMP()
  WHEN NOT MATCHED THEN
    INSERT (
      TRADE_ID, VERSION, COUNTERPARTY_ID, INSTRUMENT_ID,
      QUANTITY, PRICE, TRADE_TYPE, CURRENCY,
      TRADE_DATE, MATURITY_DATE, PROCESSED_AT, LOAD_SOURCE
    ) VALUES (
      src.TRADE_ID, src.VERSION, src.COUNTERPARTY_ID, src.INSTRUMENT_ID,
      src.QUANTITY, src.PRICE, src.TRADE_TYPE, src.CURRENCY,
      src.TRADE_DATE, src.MATURITY_DATE, src.PROCESSED_AT, src.LOAD_SOURCE
    );
END;

-- Create task for data quality checks
CREATE OR REPLACE TASK TRADE_DB.AUDIT.RUN_DATA_QUALITY_CHECKS
  WAREHOUSE = TRADE_TRANSFORM_WH
  AFTER TRADE_DB.PROCESSED.PROCESS_NEW_TRADES
AS
BEGIN
  -- Check for duplicate trades
  INSERT INTO TRADE_DB.AUDIT.DATA_QUALITY_ISSUES
  SELECT 
    CURRENT_TIMESTAMP() as CHECK_TIMESTAMP,
    'DUPLICATE_TRADE' as ISSUE_TYPE,
    TRADE_ID,
    COUNT(*) as ISSUE_COUNT,
    ARRAY_AGG(VERSION) as AFFECTED_VERSIONS
  FROM TRADE_DB.PROCESSED.VALID_TRADES
  WHERE IS_CURRENT = TRUE
  GROUP BY TRADE_ID
  HAVING COUNT(*) > 1;
  
  -- Check for trades with future trade dates
  INSERT INTO TRADE_DB.AUDIT.DATA_QUALITY_ISSUES
  SELECT 
    CURRENT_TIMESTAMP() as CHECK_TIMESTAMP,
    'FUTURE_TRADE_DATE' as ISSUE_TYPE,
    TRADE_ID,
    1 as ISSUE_COUNT,
    ARRAY_CONSTRUCT(VERSION) as AFFECTED_VERSIONS
  FROM TRADE_DB.PROCESSED.VALID_TRADES
  WHERE IS_CURRENT = TRUE
    AND TRADE_DATE > CURRENT_TIMESTAMP();
END;

-- Create task for expired trade detection
CREATE OR REPLACE TASK TRADE_DB.PROCESSED.MARK_EXPIRED_TRADES
  WAREHOUSE = TRADE_TRANSFORM_WH
  SCHEDULE = 'USING CRON 0 0 * * * UTC'  -- Daily at midnight
AS
BEGIN
  -- Update expired trades
  UPDATE TRADE_DB.PROCESSED.VALID_TRADES
  SET STATUS = 'EXPIRED',
      UPDATED_AT = CURRENT_TIMESTAMP()
  WHERE IS_CURRENT = TRUE
    AND STATUS = 'VALID'
    AND MATURITY_DATE < CURRENT_TIMESTAMP();
    
  -- Insert into expired trades table
  INSERT INTO TRADE_DB.PROCESSED.EXPIRED_TRADES
  SELECT 
    TRADE_ID, VERSION, COUNTERPARTY_ID, INSTRUMENT_ID,
    QUANTITY, PRICE, TRADE_TYPE, CURRENCY,
    TRADE_DATE, MATURITY_DATE, CURRENT_TIMESTAMP()
  FROM TRADE_DB.PROCESSED.VALID_TRADES
  WHERE IS_CURRENT = TRUE
    AND STATUS = 'EXPIRED'
    AND NOT EXISTS (
      SELECT 1 FROM TRADE_DB.PROCESSED.EXPIRED_TRADES et
      WHERE et.TRADE_ID = VALID_TRADES.TRADE_ID
        AND et.VERSION = VALID_TRADES.VERSION
    );
END;

-- Resume tasks
ALTER TASK TRADE_DB.PROCESSED.PROCESS_NEW_TRADES RESUME;
ALTER TASK TRADE_DB.AUDIT.RUN_DATA_QUALITY_CHECKS RESUME;
ALTER TASK TRADE_DB.PROCESSED.MARK_EXPIRED_TRADES RESUME;
