-- 00-infrastructure/snowflake/sql/01_setup_database.sql
-- Create database, schemas, and warehouse
-- SQL Scripts setup
-- Database: TRADE_DB
-- Schemas: RAW, PROCESSED, ANALYTICS, AUDIT
-- Virtual Warehouses: TRADE_LOAD_WH (S-SMALL), TRADE_TRANSFORM_WH (SMALL), TRADE_ANALYTICS_WF (MEDIUM)
-- Roles: TRADE_LOADER, TRADE_ANALYST, TRADE_ADMIN with different priveleges
-- 
CREATE OR REPLACE DATABASE TRADE_DB 
DATA_RETENTION_TIME_IN_DAYS = 90 
COMMENT = 'Trade processing database';

CREATE OR REPLACE SCHEMA TRADE_DB.RAW 
COMMENT = 'Raw trade data schema';

CREATE OR REPLACE SCHEMA TRADE_DB.PROCESSED 
COMMENT = 'Processed trade data schema';

CREATE OR REPLACE SCHEMA TRADE_DB.ANALYTICS 
COMMENT = 'Analytics views and aggregates';

CREATE OR REPLACE SCHEMA TRADE_DB.AUDIT 
COMMENT = 'Audit and compliance data';

-- Create virtual warehouses
CREATE OR REPLACE WAREHOUSE TRADE_LOAD_WH 
  WITH WAREHOUSE_SIZE = 'X-SMALL'
  AUTO_SUSPEND = 300
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Warehouse for data loading';

CREATE OR REPLACE WAREHOUSE TRADE_TRANSFORM_WH 
  WITH WAREHOUSE_SIZE = 'SMALL'
  AUTO_SUSPEND = 300
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Warehouse for data transformation';

CREATE OR REPLACE WAREHOUSE TRADE_ANALYTICS_WH 
  WITH WAREHOUSE_SIZE = 'MEDIUM'
  AUTO_SUSPEND = 300
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Warehouse for analytics queries';

-- Create roles and users
CREATE OR REPLACE ROLE TRADE_LOADER;
CREATE OR REPLACE ROLE TRADE_ANALYST;
CREATE OR REPLACE ROLE TRADE_ADMIN;

-- Grant privileges
GRANT USAGE ON DATABASE TRADE_DB TO ROLE TRADE_LOADER;
GRANT USAGE ON SCHEMA TRADE_DB.RAW TO ROLE TRADE_LOADER;
GRANT USAGE ON WAREHOUSE TRADE_LOAD_WH TO ROLE TRADE_LOADER;

GRANT SELECT ON ALL TABLES IN SCHEMA TRADE_DB.ANALYTICS TO ROLE TRADE_ANALYST;
GRANT USAGE ON WAREHOUSE TRADE_ANALYTICS_WH TO ROLE TRADE_ANALYST;

GRANT ALL PRIVILEGES ON DATABASE TRADE_DB TO ROLE TRADE_ADMIN;
