-- 00-infrastructure/snowflake/sql/02_create_tables.sql
-- Raw staging table with variant column for flexibility
CREATE OR REPLACE TABLE TRADE_DB.RAW.TRADES_STAGING (
    RECORD_ID NUMBER AUTOINCREMENT,
    RAW_DATA VARIANT,
    FILE_NAME STRING,
    LOAD_TIMESTAMP TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_SYSTEM STRING,
    BATCH_ID STRING
)
CLUSTER BY (DATE(LOAD_TIMESTAMP))
COMMENT = 'Raw trade data staging table'
DATA_RETENTION_TIME_IN_DAYS = 7;

-- Valid trades table
CREATE OR REPLACE TABLE TRADE_DB.PROCESSED.VALID_TRADES (
    TRADE_ID STRING NOT NULL,
    VERSION INTEGER NOT NULL,
    COUNTERPARTY_ID STRING NOT NULL,
    INSTRUMENT_ID STRING NOT NULL,
    QUANTITY INTEGER NOT NULL,
    PRICE DECIMAL(20, 6) NOT NULL,
    TRADE_TYPE STRING NOT NULL,
    CURRENCY STRING NOT NULL,
    TRADE_DATE TIMESTAMP_TZ NOT NULL,
    MATURITY_DATE TIMESTAMP_TZ NOT NULL,
    STATUS STRING DEFAULT 'VALID',
    PROCESSED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
    LOAD_ID STRING,
    VALIDATION_CHECKSUM STRING,
    
    -- Metadata
    CREATED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
    DELETED_AT TIMESTAMP_TZ,
    IS_CURRENT BOOLEAN DEFAULT TRUE,
    VALID_FROM TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
    VALID_TO TIMESTAMP_TZ DEFAULT '9999-12-31 23:59:59'
)
CLUSTER BY (
    DATE(TRADE_DATE),
    COUNTERPARTY_ID,
    STATUS
)
COMMENT = 'Valid trades with SCD Type 2 support'
DATA_RETENTION_TIME_IN_DAYS = 90;

-- Create clone for development/testing
CREATE OR REPLACE TABLE TRADE_DB.PROCESSED.VALID_TRADES_DEV 
CLONE TRADE_DB.PROCESSED.VALID_TRADES;

-- Rejected trades table
CREATE OR REPLACE TABLE TRADE_DB.AUDIT.REJECTED_TRADES (
    REJECTION_ID NUMBER AUTOINCREMENT,
    TRADE_ID STRING,
    RAW_DATA VARIANT,
    REJECTION_REASON STRING NOT NULL,
    BUSINESS_RULE_VIOLATED STRING,
    REJECTED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
    PROCESSOR_ID STRING,
    ERROR_DETAILS VARIANT,
    
    -- Index for faster queries
    INDEX REJECTION_REASON_IDX (REJECTION_REASON),
    INDEX TRADE_DATE_IDX (DATE(REJECTED_AT))
)
CLUSTER BY (DATE(REJECTED_AT), REJECTION_REASON)
COMMENT = 'Audit table for rejected trades'
DATA_RETENTION_TIME_IN_DAYS = 365;

-- Expired trades table
CREATE OR REPLACE TABLE TRADE_DB.PROCESSED.EXPIRED_TRADES (
    TRADE_ID STRING NOT NULL,
    VERSION INTEGER NOT NULL,
    COUNTERPARTY_ID STRING NOT NULL,
    INSTRUMENT_ID STRING NOT NULL,
    QUANTITY INTEGER NOT NULL,
    PRICE DECIMAL(20, 6) NOT NULL,
    TRADE_TYPE STRING NOT NULL,
    CURRENCY STRING NOT NULL,
    TRADE_DATE TIMESTAMP_TZ NOT NULL,
    MATURITY_DATE TIMESTAMP_TZ NOT NULL,
    EXPIRED_AT TIMESTAMP_TZ NOT NULL,
    EXPIRY_NOTIFICATION_SENT BOOLEAN DEFAULT FALSE,
    PROCESSED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
    
    PRIMARY KEY (TRADE_ID, VERSION)
)
CLUSTER BY (DATE(EXPIRED_AT), COUNTERPARTY_ID)
COMMENT = 'Expired trades for compliance reporting';

-- Trade audit trail
CREATE OR REPLACE TABLE TRADE_DB.AUDIT.TRADE_AUDIT_TRAIL (
    AUDIT_ID NUMBER AUTOINCREMENT,
    TRADE_ID STRING,
    ACTION STRING NOT NULL,
    ACTION_TIMESTAMP TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
    USER_NAME STRING,
    APPLICATION_NAME STRING,
    OLD_VALUES VARIANT,
    NEW_VALUES VARIANT,
    CHANGE_SUMMARY STRING
)
COMMENT = 'Complete audit trail for all trade modifications';
