-- Enable audit logging
-- Following script sets up event logging and create audit view for events
-- AUDIT.ACCOUNT_USAGE_VIEW  collects data from snowflakes ACCOUNT_USAGE.QUERY_HISTORY and populates AUDIT.ACCOUNT_USAGE_VIEWS

ALTER ACCOUNT SET 
    EVENT_TIMESTAMP_IN_TRACE = TRUE,
    TRACE_LEVEL = 'ON_EVENT';

-- Create audit view
CREATE OR REPLACE VIEW TRADE_DB.AUDIT.ACCOUNT_USAGE_VIEW AS
SELECT 
    EVENT_TIMESTAMP,
    EVENT_TYPE,
    USER_NAME,
    ROLE_NAME,
    DATABASE_NAME,
    SCHEMA_NAME,
    OBJECT_NAME,
    QUERY_TEXT,
    ERROR_CODE,
    ERROR_MESSAGE
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE DATABASE_NAME = 'TRADE_DB'
ORDER BY EVENT_TIMESTAMP DESC;
