-- Following script is used to create materialzed views and update refresh schedule
-- Create materialized views for frequent queries
-- The task REFRESH_SUMMARY_MV is applied to materialized view DAILY_SUMMARY_MV
--
CREATE OR REPLACE MATERIALIZED VIEW TRADE_DB.ANALYTICS.DAILY_SUMMARY_MV
CLUSTER BY (TRADE_DATE)
AS
SELECT 
    DATE(TRADE_DATE) as TRADE_DATE,
    COUNT(*) as TRADE_COUNT,
    SUM(QUANTITY * PRICE) as TOTAL_VALUE
FROM TRADE_DB.PROCESSED.VALID_TRADES
WHERE IS_CURRENT = TRUE
GROUP BY DATE(TRADE_DATE);

-- Schedule refresh
CREATE OR REPLACE TASK REFRESH_SUMMARY_MV
  WAREHOUSE = TRADE_TRANSFORM_WH
  SCHEDULE = 'USING CRON 0 */4 * * * UTC'
AS
  ALTER MATERIALIZED VIEW TRADE_DB.ANALYTICS.DAILY_SUMMARY_MV REFRESH;
